-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.kri_atomic (
  kri_id bigint NOT NULL,
  atomic_id integer NOT NULL,
  reporting_date integer NOT NULL,
  atomic_metadata text,
  atomic_value text,
  atomic_status integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  source text DEFAULT ''::text,
  kri_code text,
  evidence_id bigint,
  CONSTRAINT kri_atomic_pkey PRIMARY KEY (kri_id, atomic_id, reporting_date),
  CONSTRAINT kri_atomic_kri_id_reporting_date_fkey FOREIGN KEY (reporting_date) REFERENCES public.kri_item(reporting_date),
  CONSTRAINT kri_atomic_kri_id_reporting_date_fkey FOREIGN KEY (kri_id) REFERENCES public.kri_item(kri_id),
  CONSTRAINT kri_atomic_evidence_id_fkey FOREIGN KEY (evidence_id) REFERENCES public.kri_evidence(evidence_id),
  CONSTRAINT kri_atomic_kri_id_reporting_date_fkey FOREIGN KEY (kri_id) REFERENCES public.kri_item(reporting_date),
  CONSTRAINT kri_atomic_kri_id_reporting_date_fkey FOREIGN KEY (reporting_date) REFERENCES public.kri_item(kri_id)
);
CREATE TABLE public.kri_audit_trail (
  audit_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  kri_id bigint NOT NULL,
  reporting_date integer NOT NULL,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  changed_by text,
  action text NOT NULL,
  field_name text,
  old_value text,
  new_value text,
  comment text,
  kri_code text,
  CONSTRAINT kri_audit_trail_pkey PRIMARY KEY (audit_id),
  CONSTRAINT kri_audit_trail_kri_id_reporting_date_fkey FOREIGN KEY (reporting_date) REFERENCES public.kri_item(reporting_date),
  CONSTRAINT kri_audit_trail_kri_id_reporting_date_fkey FOREIGN KEY (kri_id) REFERENCES public.kri_item(reporting_date),
  CONSTRAINT kri_audit_trail_kri_id_reporting_date_fkey FOREIGN KEY (reporting_date) REFERENCES public.kri_item(kri_id),
  CONSTRAINT kri_audit_trail_kri_id_reporting_date_fkey FOREIGN KEY (kri_id) REFERENCES public.kri_item(kri_id)
);
CREATE TABLE public.kri_evidence (
  evidence_id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  kri_id bigint NOT NULL,
  reporting_date integer NOT NULL,
  file_name text NOT NULL,
  file_url text NOT NULL,
  description text,
  uploaded_by text,
  uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
  md5 text,
  CONSTRAINT kri_evidence_pkey PRIMARY KEY (evidence_id),
  CONSTRAINT kri_evidence_kri_id_reporting_date_fkey FOREIGN KEY (reporting_date) REFERENCES public.kri_item(kri_id),
  CONSTRAINT kri_evidence_kri_id_reporting_date_fkey FOREIGN KEY (kri_id) REFERENCES public.kri_item(kri_id),
  CONSTRAINT kri_evidence_kri_id_reporting_date_fkey FOREIGN KEY (reporting_date) REFERENCES public.kri_item(reporting_date),
  CONSTRAINT kri_evidence_kri_id_reporting_date_fkey FOREIGN KEY (kri_id) REFERENCES public.kri_item(reporting_date)
);
CREATE TABLE public.kri_item (
  kri_id bigint NOT NULL,
  reporting_date integer NOT NULL,
  kri_code text NOT NULL,
  metadata_effective_date timestamp with time zone,
  kri_value text,
  kri_status integer,
  source text DEFAULT ''::text,
  evidence_id bigint,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT kri_item_pkey PRIMARY KEY (kri_id, reporting_date),
  CONSTRAINT fk_kri_item_metadata FOREIGN KEY (kri_code) REFERENCES public.kri_metadata(kri_code),
  CONSTRAINT fk_kri_item_evidence FOREIGN KEY (evidence_id) REFERENCES public.kri_evidence(evidence_id)
);
CREATE TABLE public.kri_metadata (
  metadata_id bigint NOT NULL DEFAULT nextval('kri_metadata_metadata_id_seq'::regclass),
  kri_code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  formula text,
  owner text,
  data_provider text,
  l1_risk_type text,
  l2_risk_type text,
  ras_metric text,
  breach_type text,
  limit_value integer,
  warning_line_value integer,
  negative_warning integer DEFAULT 0,
  negative_limit integer DEFAULT 0,
  reporting_frequency text,
  is_calculated_kri boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone,
  CONSTRAINT kri_metadata_pkey PRIMARY KEY (metadata_id)
);
CREATE TABLE public.kri_user (
  UUID uuid NOT NULL DEFAULT gen_random_uuid(),
  User_ID character varying NOT NULL,
  User_Name character varying,
  Department character varying,
  OTHER_INFO text DEFAULT 'anything'::text,
  user_role character varying DEFAULT 'user'::character varying CHECK (user_role::text = ANY (ARRAY['user'::character varying, 'dept_admin'::character varying, 'admin'::character varying]::text[])),
  CONSTRAINT kri_user_pkey PRIMARY KEY (UUID)
);
CREATE TABLE public.kri_user_permission (
  user_uuid uuid NOT NULL,
  kri_id bigint NOT NULL,
  reporting_date integer NOT NULL,
  actions character varying NOT NULL DEFAULT ''::character varying,
  effect boolean DEFAULT true,
  condition json,
  created_date timestamp without time zone DEFAULT now(),
  update_date timestamp without time zone DEFAULT now(),
  kri_code text,
  CONSTRAINT kri_user_permission_pkey PRIMARY KEY (user_uuid, kri_id, reporting_date),
  CONSTRAINT kri_user_permission_kri_id_reporting_date_fkey FOREIGN KEY (reporting_date) REFERENCES public.kri_item(kri_id),
  CONSTRAINT kri_user_permission_kri_id_reporting_date_fkey FOREIGN KEY (reporting_date) REFERENCES public.kri_item(reporting_date),
  CONSTRAINT kri_user_permission_user_uuid_fkey FOREIGN KEY (user_uuid) REFERENCES public.kri_user(UUID),
  CONSTRAINT kri_user_permission_kri_id_reporting_date_fkey FOREIGN KEY (kri_id) REFERENCES public.kri_item(kri_id),
  CONSTRAINT kri_user_permission_kri_id_reporting_date_fkey FOREIGN KEY (kri_id) REFERENCES public.kri_item(reporting_date)
);
CREATE TABLE public.metadata_history (
  history_id bigint NOT NULL DEFAULT nextval('metadata_history_history_id_seq'::regclass),
  metadata_id bigint NOT NULL,
  kri_code text NOT NULL,
  name text NOT NULL,
  description text,
  formula text,
  owner text,
  data_provider text,
  l1_risk_type text,
  l2_risk_type text,
  ras_metric text,
  breach_type text,
  limit_value integer,
  warning_line_value integer,
  negative_warning integer DEFAULT 0,
  negative_limit integer DEFAULT 0,
  reporting_frequency text,
  is_calculated_kri boolean NOT NULL,
  effective_from timestamp with time zone NOT NULL,
  effective_to timestamp with time zone,
  changed_by text,
  changed_at timestamp with time zone NOT NULL DEFAULT now(),
  change_reason text,
  CONSTRAINT metadata_history_pkey PRIMARY KEY (history_id),
  CONSTRAINT fk_metadata_history_metadata FOREIGN KEY (metadata_id) REFERENCES public.kri_metadata(metadata_id)
);