create table public.kri_item (
  kri_id bigint not null,
  reporting_date integer not null,
  kri_name text null,        -- name of the kri
  kri_description text null, -- description of the kri
  data_provider text null,   -- Data Provider :
  kri_owner text null,       -- KRI Owner     :
  l1_risk_type text null,
  l2_risk_type text null,
  ras_metric text null,
  breach_type text null,
  limit_value integer null,
  warning_line_value integer null,
  reporting_frequency text null,
  kri_formula text null,
  kri_value text null,       -- Inputed or Calculated from atomic values( Lock if calculated)
  kri_status integer null,   -- 10: Pending Input, 20: Adjusting, 30: Pending Data Provider Approval, 40: Ready for submission, 50: Submitted, 60: Finalized
  created_at timestamp with time zone not null default now(),
  constraint kri_item_pkey primary key (kri_id, reporting_date)
) TABLESPACE pg_default;

create table public.kri_atomic (
  kri_id bigint not null,
  atomic_id integer not null,
  reporting_date integer not null,
  atomic_metadata text null,            -- description of the atomic value (sub-kri display)
  atomic_value text null,               -- inputed value
  atomic_status integer null,           -- 10: Pending Input, 20: Adjusting, 30: Pending Data Provider Approval, 40: Ready for submission, 50: Submitted, 60: Finalized
  created_at timestamp with time zone not null default now(),
  constraint kri_atomic_pkey primary key (kri_id, reporting_date, atomic_id),
  constraint fk_kri_item_snapshot foreign KEY (kri_id, reporting_date) references kri_item (kri_id, reporting_date) on delete CASCADE
) TABLESPACE pg_default;

create table public.kri_evidence (
  evidence_id bigint generated by default as identity not null,
  kri_id bigint not null,
  reporting_date integer not null,
  file_name text not null,     -- name of the file (future)
  file_url text not null,      -- url of the file (future)
  description text null,
  uploaded_by text null,
  uploaded_at timestamp with time zone not null default now(),
  constraint kri_evidence_pkey primary key (evidence_id),
  constraint fk_kri_item_evidence foreign KEY (kri_id, reporting_date) references kri_item (kri_id, reporting_date) on delete CASCADE
) TABLESPACE pg_default;

create table public.kri_audit_trail (
  audit_id bigint generated by default as identity not null,
  kri_id bigint not null,
  reporting_date integer not null,
  changed_at timestamp with time zone not null default now(),
  changed_by text null,
  action text not null,
  field_name text null,
  old_value text null,
  new_value text null,
  comment text null,            -- comment for the audit trail, only required if rejected
  constraint kri_audit_trail_pkey primary key (audit_id),
  constraint fk_kri_item_audit foreign KEY (kri_id, reporting_date) references kri_item (kri_id, reporting_date) on delete CASCADE
) TABLESPACE pg_default;